### ISSUE TITLE
프사좀 제발제발제발 진짜 바꿔주세요 ㅠㅠ

### ISSUE THREAD

**Issue by shw0471** [eungyeole/eungyeole#2]
볼때마다 화가나고 치가떨려서 참지를 못하겠어요 ㅠㅠ

**Comment by shw0471** [comment]
ㅇㅈ합니다..

**Comment by kimxwan0319** [comment]
(#1) <- 이거 같은 이슌데 해결안하고 닫으셨네요ㅠㅠ

**Comment by shw0471** [comment]
- [ ] 프사 바꾸기
- [ ] 사과문 올리기
- [ ] 밥한끼 사기

**Comment by eungyeole** [comment]
WWDC 개발자아닌사람은 쳐다도 보지않습니다.
